### ISSUE TITLE
Payment successfull but the order status still showing payment pending.

### ISSUE THREAD

**Issue by sonu769** [fooman/magebase_paymentexpress#8]
We have a Magento 1.7.0.2 website. Everything was working fine till now and we haven't updated anything, but recently the orders emails stopped coming through and order status shows payment pending although the payment is made successfully and there is no payment details. Do you have come across any similar issue.  Thanks for your help.

**Comment by fooman** [comment]
Please check that the dps instant payment notification reaches your server. You can review the server access logs as well as the Magento logs to confirm. If these are missing please get in touch with PaymentExpress to inquire as to why they are not being sent.

**Comment by acndr** [comment]
I have the same problem happening at the moment, magento 1.8.1

**Comment by sonu769** [comment]
Hi again, 
      I contacted PaymentExpress support team. And they told that All the FPRN(fail proof result notification) were sent successfully and the website responded saying it had received this. So I think everything's fine as far as PaymentExpress is concerned. Do you have any idea what could be the other problem. Thanks for your help.

**Comment by fooman** [comment]
Please check the troubleshooting section here https://github.com/fooman/magebase_paymentexpress/wiki/Troubleshooting and report back with the relevant log entries.

**Comment by acndr** [comment]
Sonu try updating your DPS module to latest version, worked for us

**Comment by fooman** [comment]
No further details received in over a month - closing this for now.
