### ISSUE TITLE
PaymentExpress to only support TLS v1.2 going forward

### ISSUE THREAD

**Issue by gdhnz** [fooman/magebase_paymentexpress#9]
We've just received an email from Payment Express to say we need to migrate to TLS v1.2 when communicating with their api.

Currently, the socket adapter this extension uses defaults to ssl. 

To support TLS v1.2, the following config option will need to be added to all the Zend_Http_Client config arrays in Model/Method/Pxpost.php and Model/Method/Pxpay.php

```
'ssltransport' => 'tlsv1.2'
```

https://stackoverflow.com/questions/37724512/zend-http-client-and-tls-1-2-in-zend-framework-1

**Comment by fooman** [comment]
@gdhnz thanks for this report. On my tests so far the system automatically chose the correct TLS version during the SSL handshake:

![snip20180416_35](https://user-images.githubusercontent.com/455508/38786035-6b8bd246-4179-11e8-8617-2691ec5871fd.png)

However I just tagged version 1.5.22 which includes the above configuration as you suggested. Feel free to re-open if this doesn't solve it for you.

**Comment by fooman** [comment]
One thing to note - if you are still on the outdated php 5.5 version you might encounter this error:

`exception 'Zend_Http_Client_Adapter_Exception' with message 'Unable to Connect to tlsv1.2://sec.paymentexpress.com:443. Error #0: Unable to find the socket transport "tlsv1.2" - did you forget to enable it when you configured PHP?'`

You would need to use at least php 5.6 to allow TLS 1.2 connections.
